### ISSUE TITLE
Add root user to postgres users

### ISSUE THREAD

**Issue by regnatpopulus** [dhis2/dhis2-server-tools#4]
Without adding the root user in the postgres container to the postgres user group using this comand:
`sudo -u postgres createuser -s root`
There is an error when running psql as shown below:
`error could not connect to database template1: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: role "root" does not exist`

**Comment by tkipkurgat** [comment]
Will be added in next release iteration

**Comment by tkipkurgat** [comment]
This is now fixed
